steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/gcp-final-task-project/kubernetes-client-sandbox:$SHORT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-west1-docker.pkg.dev/gcp-final-task-project/kubernetes-client-sandbox:$SHORT_SHA' ]
images: [ 'europe-west1-docker.pkg.dev/gcp-final-task-project/kubernetes-client-sandbox:$SHORT_SHA' ]
