steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/kubernetes-client-sandbox/sandbox-app:$SHORT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/kubernetes-client-sandbox/sandbox-app:$SHORT_SHA' ]
images: [ 'europe-west1-docker.pkg.dev/$PROJECT_ID/kubernetes-client-sandbox/sandbox-app:$SHORT_SHA' ]
